from __future__ import annotations

import os
from typing import Any, Literal

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_groq import ChatGroq
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

# ============================================================
# LLM OUTPUT SCHEMAS
# ============================================================


class OrderItemPayload(BaseModel):
    """
    Structured representation of one item extracted from
    the user's natural-language order.
    """

    model_config = ConfigDict(extra="forbid")

    dish_name: str = Field(
        ...,
        min_length=1,
        description="Name of the requested dish.",
    )

    requested_quantity: int = Field(
        ...,
        gt=0,
        description="Positive integer quantity requested by the user.",
    )

    @field_validator("dish_name")
    @classmethod
    def normalize_dish_name(cls, value: str) -> str:
        """
        Normalize obvious whitespace/casing variations.

        Inventory/menu matching should still be handled by the
        deterministic application layer.
        """
        normalized = " ".join(value.strip().lower().split())

        if not normalized:
            raise ValueError("dish_name cannot be empty")

        return normalized


class OrderExtractionPayload(BaseModel):
    """
    Structured semantic result produced by the order parser LLM.

    IMPORTANT:
    This model represents language understanding only.

    It does NOT contain:
    - inventory information
    - order status
    - retry counters
    - routing instructions
    - workflow commands
    """

    model_config = ConfigDict(extra="forbid")

    intent: Literal[
        "food_order",
        "incomplete_order",
        "unrelated",
        "ambiguous",
    ] = Field(
        ...,
        description="Semantic intent of the user's message.",
    )

    order_items: list[OrderItemPayload] = Field(
        default_factory=list,
        description="Items extracted from the user's message.",
    )

    @model_validator(mode="after")
    def validate_semantic_consistency(self) -> "OrderExtractionPayload":
        """
        Ensure that the semantic result is internally consistent.

        A valid food order must contain at least one item.
        Non-order intents should not carry order items.
        """

        if self.intent == "food_order" and not self.order_items:
            raise ValueError("food_order intent requires at least one order item")

        if (
            self.intent
            in {
                "incomplete_order",
                "unrelated",
                "ambiguous",
            }
            and self.order_items
        ):
            raise ValueError(f"{self.intent} intent must not contain order items")

        return self


class PartialDecisionPayload(BaseModel):
    """
    Structured semantic interpretation of a user's response
    to a partial-order proposal.
    """

    model_config = ConfigDict(extra="forbid")

    decision: Literal[
        "ACCEPT_PARTIAL",
        "NEW_ORDER",
        "AMBIGUOUS",
    ] = Field(
        ...,
        description="User's decision regarding the partial order.",
    )


class ResponsePayload(BaseModel):
    """
    Structured response generated by the response LLM.

    Keeping the response itself in a schema makes it easier to
    validate the LLM result before returning it to the application.
    """

    model_config = ConfigDict(extra="forbid")

    response: str = Field(
        ...,
        min_length=1,
        description="Concise user-facing response.",
    )

    @field_validator("response")
    @classmethod
    def clean_response(cls, value: str) -> str:
        return value.strip()


# ============================================================
# LLM SERVICE
# ============================================================


class LLMService:
    """
    LLM service used by Order-Pilot.

    Responsibilities:
        - Natural-language understanding
        - Structured semantic extraction
        - Partial-order decision interpretation
        - Natural-language response generation

    This service MUST NOT:
        - modify LangGraph state
        - inspect inventory directly
        - modify retry counters
        - determine workflow transitions
        - execute business operations
        - directly call cook/serve services

    The LangGraph/application layer remains responsible for those
    operations.
    """

    DEFAULT_MODEL = "openai/gpt-oss-120b"

    def __init__(
        self,
        model_name: str | None = None,
        api_key: str | None = None,
        temperature: float = 0.0,
    ) -> None:
        """
        Initialize the Groq-backed LLM service.

        Environment variables:

            GROQ_API_KEY
            ORDER_PILOT_MODEL (optional)

        Example:

            GROQ_API_KEY=your_key
            ORDER_PILOT_MODEL=openai/gpt-oss-120b
        """

        self.model_name = (
            model_name or os.getenv("ORDER_PILOT_MODEL") or self.DEFAULT_MODEL
        )

        self.api_key = api_key or os.getenv("GROQ_API_KEY")

        self.temperature = temperature

        self._chat_model: ChatGroq | None = None

        self._load_model()

    # ========================================================
    # MODEL INITIALIZATION
    # ========================================================

    def _load_model(self) -> None:
        """
        Initialize the Groq chat model.

        We deliberately fail gracefully when the API key is not
        configured so the rest of the application can still use
        deterministic fallback responses where appropriate.
        """

        if not self.api_key:
            return

        self._chat_model = ChatGroq(
            model=self.model_name,
            api_key=self.api_key,
            temperature=self.temperature,
        )

    @property
    def available(self) -> bool:
        """
        Return whether the LLM is configured and available.
        """

        return self._chat_model is not None

    def _require_model(self) -> ChatGroq:
        """
        Return the configured model or raise a clear error.
        """

        if self._chat_model is None:
            raise RuntimeError(
                "Groq LLM is not configured. "
                "Set the GROQ_API_KEY environment variable."
            )

        return self._chat_model

    # ========================================================
    # ORDER PARSING
    # ========================================================

    def parse_order_message(
        self,
        text: str,
    ) -> dict[str, Any]:
        """
        Parse a user message into structured order semantics.

        Example:

            "I want two burgers and one pizza"

        becomes:

            {
                "intent": "food_order",
                "order_items": [
                    {
                        "dish_name": "burger",
                        "requested_quantity": 2
                    },
                    {
                        "dish_name": "pizza",
                        "requested_quantity": 1
                    }
                ]
            }

        This method does NOT:
            - check inventory
            - consume an order attempt
            - change workflow state
            - route to another LangGraph node
        """

        cleaned_text = self._validate_user_text(text)

        model = self._require_model()

        structured_model = model.with_structured_output(OrderExtractionPayload)

        messages = [
            SystemMessage(
                content=(
                    "You are the semantic parser for Order-Pilot, "
                    "a restaurant food-ordering assistant.\n\n"
                    "Your only responsibility is to understand the "
                    "user's message and extract semantic information.\n\n"
                    "Classify the message into exactly one of:\n"
                    "- food_order\n"
                    "- incomplete_order\n"
                    "- unrelated\n"
                    "- ambiguous\n\n"
                    "For food_order, extract every explicitly requested "
                    "dish and its quantity.\n\n"
                    "Rules:\n"
                    "1. Never check inventory.\n"
                    "2. Never assume inventory availability.\n"
                    "3. Never create workflow commands.\n"
                    "4. Never create retry instructions.\n"
                    "5. Never determine order status.\n"
                    "6. Never invent dishes or quantities.\n"
                    "7. If quantity is missing or cannot be determined, "
                    "use incomplete_order.\n"
                    "8. If the message is unrelated to ordering food, "
                    "use unrelated.\n"
                    "9. If the meaning cannot be reliably determined, "
                    "use ambiguous.\n"
                    "10. Quantities must be positive integers."
                )
            ),
            HumanMessage(content=cleaned_text),
        ]

        try:
            result = structured_model.invoke(messages)

        except Exception as exc:
            raise RuntimeError(f"Order semantic parsing failed: {exc}") from exc

        validated = self._validate_order_extraction(result)

        return {
            "intent": validated.intent,
            "order_items": [
                {
                    "dish_name": item.dish_name,
                    "requested_quantity": item.requested_quantity,
                }
                for item in validated.order_items
            ],
        }

    # ========================================================
    # PARTIAL ORDER DECISION
    # ========================================================

    def parse_partial_decision(
        self,
        text: str,
    ) -> str:
        """
        Interpret the user's response to a partial-order proposal.

        Examples:

            "Yes, I'll take what you have."
                -> ACCEPT_PARTIAL

            "No, give me something else."
                -> NEW_ORDER

            "Maybe."
                -> AMBIGUOUS

        This method only interprets language.

        It does NOT:
            - accept the order
            - reject the order
            - modify order state
            - trigger a new order
            - route the graph
        """

        cleaned_text = self._validate_user_text(text)

        model = self._require_model()

        structured_model = model.with_structured_output(PartialDecisionPayload)

        messages = [
            SystemMessage(
                content=(
                    "You interpret a user's response to a partial "
                    "restaurant-order proposal.\n\n"
                    "Return exactly one semantic decision:\n"
                    "- ACCEPT_PARTIAL: the user clearly accepts the "
                    "available portion.\n"
                    "- NEW_ORDER: the user clearly rejects the available "
                    "portion and wants to submit a different order.\n"
                    "- AMBIGUOUS: the user's response does not clearly "
                    "indicate either decision.\n\n"
                    "Do not guess.\n"
                    "Do not interpret unrelated information as acceptance.\n"
                    "Do not execute any action.\n"
                    "Only classify the user's meaning."
                )
            ),
            HumanMessage(content=cleaned_text),
        ]

        try:
            result = structured_model.invoke(messages)

        except Exception as exc:
            raise RuntimeError(f"Partial-order decision parsing failed: {exc}") from exc

        validated = self._validate_partial_decision(result)

        return validated.decision

    # ========================================================
    # RESPONSE GENERATION
    # ========================================================

    def generate_response(
        self,
        kind: str,
        context: dict[str, Any] | None = None,
    ) -> str:
        """
        Generate a natural-language response from structured
        application facts.

        IMPORTANT:

        The LLM is a presentation layer here.

        It must NOT invent:
            - inventory quantities
            - order status
            - retry counts
            - successful operations
            - failures
            - prices
            - dishes

        All business facts must come from `context`.
        """

        normalized_context = context or {}

        if not self.available:
            return self._fallback_response(
                kind,
                normalized_context,
            )

        model = self._require_model()

        structured_model = model.with_structured_output(ResponsePayload)

        messages = [
            SystemMessage(
                content=(
                    "You are the response-generation component of "
                    "Order-Pilot, a restaurant ordering assistant.\n\n"
                    "Generate a concise, polite, natural-language "
                    "response for the user.\n\n"
                    "IMPORTANT:\n"
                    "1. Use ONLY facts explicitly provided in the "
                    "application context.\n"
                    "2. Never invent inventory quantities.\n"
                    "3. Never invent order status.\n"
                    "4. Never invent prices.\n"
                    "5. Never claim an operation succeeded unless "
                    "the context explicitly says it succeeded.\n"
                    "6. Never claim an operation failed unless "
                    "the context explicitly says it failed.\n"
                    "7. Never modify business state.\n"
                    "8. Never give workflow instructions that are "
                    "not supported by the context.\n"
                    "9. Keep the response concise.\n"
                    "10. If the user needs to provide information, "
                    "clearly ask for it."
                )
            ),
            HumanMessage(
                content=(
                    f"Response type: {kind}\n\n"
                    f"Application context:\n"
                    f"{self._safe_context_string(normalized_context)}"
                )
            ),
        ]

        try:
            result = structured_model.invoke(messages)

        except Exception:
            # Response generation is presentation-layer behavior.
            # If it fails, use a deterministic fallback rather than
            # turning a successful business operation into a workflow
            # failure.
            return self._fallback_response(
                kind,
                normalized_context,
            )

        validated = self._validate_response(result)

        return validated.response

    # ========================================================
    # VALIDATION HELPERS
    # ========================================================

    @staticmethod
    def _validate_user_text(text: str) -> str:
        """
        Validate and normalize raw user text before sending it
        to the LLM.
        """

        if not isinstance(text, str):
            raise TypeError("User message must be a string.")

        cleaned = text.strip()

        if not cleaned:
            raise ValueError("User message cannot be empty.")

        return cleaned

    @staticmethod
    def _validate_order_extraction(
        result: Any,
    ) -> OrderExtractionPayload:
        """
        Validate structured output from the order parser.

        `with_structured_output()` normally returns the Pydantic
        model directly, but this method also handles dictionary
        results defensively.
        """

        if isinstance(result, OrderExtractionPayload):
            return result

        try:
            return OrderExtractionPayload.model_validate(result)
        except ValidationError as exc:
            raise RuntimeError(
                f"Invalid order extraction returned by LLM: {exc}"
            ) from exc

    @staticmethod
    def _validate_partial_decision(
        result: Any,
    ) -> PartialDecisionPayload:
        """
        Validate structured partial-order decision.
        """

        if isinstance(result, PartialDecisionPayload):
            return result

        try:
            return PartialDecisionPayload.model_validate(result)
        except ValidationError as exc:
            raise RuntimeError(
                f"Invalid partial-order decision returned by LLM: {exc}"
            ) from exc

    @staticmethod
    def _validate_response(
        result: Any,
    ) -> ResponsePayload:
        """
        Validate generated user-facing response.
        """

        if isinstance(result, ResponsePayload):
            return result

        try:
            return ResponsePayload.model_validate(result)
        except ValidationError as exc:
            raise RuntimeError(f"Invalid response returned by LLM: {exc}") from exc

    # ========================================================
    # CONTEXT HANDLING
    # ========================================================

    @staticmethod
    def _safe_context_string(
        context: dict[str, Any],
    ) -> str:
        """
        Convert application context into a predictable string.

        The context is application-generated structured data,
        not raw model-controlled workflow state.
        """

        try:
            import json

            return json.dumps(
                context,
                ensure_ascii=False,
                default=str,
                indent=2,
            )
        except (TypeError, ValueError):
            return str(context)

    # ========================================================
    # FALLBACK RESPONSES
    # ========================================================

    @staticmethod
    def _fallback_response(
        kind: str,
        context: dict[str, Any] | None = None,
    ) -> str:
        """
        Deterministic response fallback.

        These responses are intentionally conservative and do not
        invent business facts.
        """

        context = context or {}

        if kind == "unrelated":
            return (
                "I'm Order-Pilot, a restaurant ordering assistant. "
                "I can help you place food orders."
            )

        if kind == "clarify":
            dish_name = context.get("dish_name")

            if dish_name:
                return f"How many {dish_name} would you like?"

            return (
                "Please provide the quantity for the item " "you would like to order."
            )

        if kind == "partial":
            items = context.get("items")

            if isinstance(items, list) and items:
                descriptions: list[str] = []

                for item in items:
                    if not isinstance(item, dict):
                        continue

                    dish_name = item.get("dish_name")
                    available = item.get("available_quantity")

                    if dish_name and isinstance(available, int):
                        descriptions.append(f"{available} {dish_name}")

                if descriptions:
                    available_text = ", ".join(descriptions)

                    return (
                        f"We currently have {available_text} available. "
                        "Would you like to proceed with the available "
                        "items or place a different order?"
                    )

            return (
                "We currently have only part of your order available. "
                "Would you like to proceed with the available items "
                "or place a different order?"
            )

        if kind == "success":
            return "Your order has been prepared and served successfully. " "Thank you!"

        if kind == "failure":
            return (
                "I'm sorry, but we weren't able to complete your order "
                "after the available attempts. Please try again later."
            )

        if kind == "cook_failure":
            return (
                "I'm sorry, we couldn't prepare your order successfully. "
                "We'll try again."
            )

        if kind == "serve_failure":
            return (
                "I'm sorry, we couldn't complete the serving step. "
                "We'll try again if another attempt is available."
            )

        if kind == "new_order":
            return "Please provide the new food order you'd like to place."

        if kind == "ambiguous":
            return (
                "I didn't quite understand your response. "
                "Please let me know whether you'd like to accept "
                "the available items or place a new order."
            )

        if kind == "invalid_order":
            return (
                "I couldn't understand that as a complete food order. "
                "Please specify the dish and quantity."
            )

        if kind == "llm_error":
            return "I couldn't process that request. " "Please try again."

        return "Please provide a valid food order."


# ============================================================
# OPTIONAL DEFAULT INSTANCE
# ============================================================

# This can be imported by the rest of the application:
#
#     from src.services.llm_service import llm_service
#
# The model is initialized lazily with the configured environment.
llm_service = LLMService()
